config/routes.rb
Rails.application.routes.draw do

resources :posts do
resources :comments  
end

root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def index
@post = Post.find(params[:post_id])#finds a parameter 
@comments =  @post.comments 
=begin
find the above id comment in comment table
=end
  end

  def show
  end

  def create
@post = find_post_parmas
@comment = @post.comments.new(set_db)
@comment.save
  end

  def new

  end

  def edit
@post = find_post_parmas
@comment = @post.comments.find(params[:id])
  end

  def update
@post = find_post_parmas
@comment = @post.comments.find(params[:id])
@comment.update_attributes(set_db)
  end

  def delete
  end

  def destroy
  end

  private
  def set_db
params.require(:comment).permit(:user_name, :user_comment)
  end

  def find_post_parmas
Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
   @post =Post.new
  end

  def create
  @post = Post.new(set_db)
  if @post.save
  redirect_to(:action => 'index')
  end
  end

  def edit
  @post = Post.find(params[:id])

  end

  def update
  @post = Post.find(params[:id])
  @post.update(set_db)
  if  @post.save
  redirect_to(:action => "index")
  else
    puts "User Could Not Updated"
  end
  end

  def delete
  end

  def destroy
    @post =  Post.find(params[:id])
    if @post.destroy
redirect_to(:action => "index")
end
  end

  private 
  def set_db
    params.require(:post).permit(:topic, :user_name, :user_post)
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>
<%= form_for @comment , url:{:action =>"update"} do |f|%>
<%= f.text_field :user_name%>
<%= f.text_field :user_comment%>
<%= f.submit("post a comment")%>
<%end%>	

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

<%@comments.each do |c|%>
<%=c.user_name%>
<%= link_to("Edit update", edit_post_comment_path(@post, c.id))%>
<%=c.user_comment%>
<br>

<%end%>
<%= link_to("New Comment",new_post_comment_path(@post))%>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<%= form_for :comment , url:{:action =>"create"} do |f|%>
<%= f.text_field :user_name%>
<%= f.text_field :user_comment%>
<%= f.submit("post a comment")%>
<%end%>	

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyForum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_footer.html.erb
<p>Copyright @ surya Prasad siwakoti, 2015</p>

app/views/posts/_form.html.erb
<%=render "header"%>
<%=form_for (@post) do|f|%>
<%=f.text_field :topic%>
<%=f.text_field :user_name%>
<%=f.text_field :user_post%>
<%=f.submit("submit")%>
<%end%>
<%=render "footer"%>

app/views/posts/_header.html.erb
<h1>Welcome To Ruby And Rails Forum</h1>
<h3> This Forum aims to connect ruby on rails lovers </h3>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%=render "form"%>

app/views/posts/index.html.erb
<%=render "header"%>
<%=link_to("Create A New Post",{:action => "new"})%>
<%@posts.each do |all|%>
<br>
<%=link_to(all.topic,{:action =>"show", :id => all.id})%>
<%=link_to("Edit/Update",{:action =>"edit", :id => all.id})%>
<%=link_to("delete",all, method: :delete)%>
<br>
<%=all.created_at%>
<%end%>
<%= render "footer"%>

app/views/posts/new.html.erb
<%=render "form"%>
<h2>Fill below Field To comment</h2>
<%= form_for @post do |f|%>
<%=f.text_field :user_name%>
<%=f.text_field :user_comment%>
<%end%>

app/views/posts/show.html.erb
<%= render "header"%>
<%= link_to("Go Back", {:action=>"index"})%>
<%= @post.topic%>
<%= @post.user_name%>
<%= @post.user_post%>
<%= render "footer"%>

<h2>Post a Comment</h2>
<%=link_to("Comment On a Post", post_comments_path(@post))%>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>